In [19]:
import pandas as pd
from sodapy import Socrata
import datetime as dt
import requests

In [ ]:
#method 1
client = Socrata("data.sfgov.org", None)
results = client.get("vw6y-z8j6", limit=10)
df = pd.DataFrame.from_records(results)
df.head()

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

In [227]:
#date to search from then to now for new data pull currently set to two days ago
query_date = str(dt.date.today() - dt.timedelta(days= 2))

In [228]:
query_date

'2026-02-08'

In [229]:
#method 2 - actually works
url = f"https://data.sfgov.org/resource/vw6y-z8j6.json?$where=updated_datetime>='{query_date}'&$limit=999999"
response = requests.get(url)
collection = response.json()
df = pd.DataFrame(collection)
df['requested_datetime'] = pd.to_datetime(df['requested_datetime'])
df.sort_values(by='requested_datetime', inplace=True, ascending=True)
df.head()

,service_request_id,requested_datetime,updated_datetime,status_description,status_notes,agency_responsible,service_name,service_subtype,service_details,address,...,lat,long,point,point_geom,source,media_url,data_as_of,data_loaded_at,street,closed_date
1478,101001291088,2025-01-10 10:47:53,2026-02-08T12:17:41.000,Closed,Case is a Duplicate,MTA - Transportation Engineering,General Request,municipal_transportation_agency,paint_shop request_for_service,"INTERSECTION LARKIN ST, BUSH ST, SAN FRANCISCO...",...,37.788909591,-122.4186558658,"{'latitude': '37.788909591', 'longitude': '-12...","{'type': 'Point', 'coordinates': [-122.4186558...",Phone,NaN,2026-02-10T01:00:00.000,2026-02-10T03:05:43.000,LARKIN ST,2026-02-08T12:17:41.000
828,101001586728,2025-03-09 21:25:00,2026-02-08T10:03:02.000,Closed,Case is a Duplicate,MTA - Transportation Engineering,General Request,municipal_transportation_agency,paint_shop request_for_service,"1006 HARRISON ST, SAN FRANCISCO, CA 94103",...,37.77707864709086,-122.40443243095288,"{'latitude': '37.77707864709086', 'longitude':...","{'type': 'Point', 'coordinates': [-122.4044324...",Mobile,NaN,2026-02-10T01:00:00.000,2026-02-10T03:05:43.000,HARRISON ST,2026-02-08T10:03:02.000
832,101001587255,2025-03-10 07:31:45,2026-02-08T10:03:35.000,Closed,Case Resolved - reds repainted,MTA - Transportation Engineering,Graffiti Public,not_offensive,sidewalk_in_front_of_property,"3800 FOLSOM ST, SAN FRANCISCO, CA 94110",...,37.73882505793709,-122.41342823129987,"{'latitude': '37.73882505793709', 'longitude':...","{'type': 'Point', 'coordinates': [-122.4134282...",Mobile,{'url': 'https://spot-sf-res.cloudinary.com/im...,2026-02-10T01:00:00.000,2026-02-10T03:05:43.000,FOLSOM ST,2026-02-08T10:03:35.000
1792,101001754174,2025-04-11 19:33:50,2026-02-08T13:03:33.000,Open,open,311 - Supervisor,General Request,municipal_transportation_agency,paint_shop request_for_service,"INTERSECTION EXCELSIOR AVE, NAPLES ST, SAN FRA...",...,37.72396161026644,-122.42888429572184,"{'latitude': '37.72396161026644', 'longitude':...","{'type': 'Point', 'coordinates': [-122.4288842...",Mobile,NaN,2026-02-10T01:00:00.000,2026-02-10T03:05:43.000,EXCELSIOR AVE,NaN
1783,101001812451,2025-04-23 15:03:37,2026-02-08T13:02:39.000,Open,open,311 - Supervisor,General Request,municipal_transportation_agency,paint_shop request_for_service,"INTERSECTION MONTEREY BLVD, EL VERANO WAY, SAN...",...,37.7300219512,-122.4617366428,"{'latitude': '37.7300219512', 'longitude': '-1...","{'type': 'Point', 'coordinates': [-122.4617366...",Phone,NaN,2026-02-10T01:00:00.000,2026-02-10T03:05:43.000,MONTEREY BLVD,NaN

In [230]:
df.sort_values(by='requested_datetime', inplace=True, ascending=True)
df.head()

,service_request_id,requested_datetime,updated_datetime,status_description,status_notes,agency_responsible,service_name,service_subtype,service_details,address,...,lat,long,point,point_geom,source,media_url,data_as_of,data_loaded_at,street,closed_date
1478,101001291088,2025-01-10 10:47:53,2026-02-08T12:17:41.000,Closed,Case is a Duplicate,MTA - Transportation Engineering,General Request,municipal_transportation_agency,paint_shop request_for_service,"INTERSECTION LARKIN ST, BUSH ST, SAN FRANCISCO...",...,37.788909591,-122.4186558658,"{'latitude': '37.788909591', 'longitude': '-12...","{'type': 'Point', 'coordinates': [-122.4186558...",Phone,NaN,2026-02-10T01:00:00.000,2026-02-10T03:05:43.000,LARKIN ST,2026-02-08T12:17:41.000
828,101001586728,2025-03-09 21:25:00,2026-02-08T10:03:02.000,Closed,Case is a Duplicate,MTA - Transportation Engineering,General Request,municipal_transportation_agency,paint_shop request_for_service,"1006 HARRISON ST, SAN FRANCISCO, CA 94103",...,37.77707864709086,-122.40443243095288,"{'latitude': '37.77707864709086', 'longitude':...","{'type': 'Point', 'coordinates': [-122.4044324...",Mobile,NaN,2026-02-10T01:00:00.000,2026-02-10T03:05:43.000,HARRISON ST,2026-02-08T10:03:02.000
832,101001587255,2025-03-10 07:31:45,2026-02-08T10:03:35.000,Closed,Case Resolved - reds repainted,MTA - Transportation Engineering,Graffiti Public,not_offensive,sidewalk_in_front_of_property,"3800 FOLSOM ST, SAN FRANCISCO, CA 94110",...,37.73882505793709,-122.41342823129987,"{'latitude': '37.73882505793709', 'longitude':...","{'type': 'Point', 'coordinates': [-122.4134282...",Mobile,{'url': 'https://spot-sf-res.cloudinary.com/im...,2026-02-10T01:00:00.000,2026-02-10T03:05:43.000,FOLSOM ST,2026-02-08T10:03:35.000
1792,101001754174,2025-04-11 19:33:50,2026-02-08T13:03:33.000,Open,open,311 - Supervisor,General Request,municipal_transportation_agency,paint_shop request_for_service,"INTERSECTION EXCELSIOR AVE, NAPLES ST, SAN FRA...",...,37.72396161026644,-122.42888429572184,"{'latitude': '37.72396161026644', 'longitude':...","{'type': 'Point', 'coordinates': [-122.4288842...",Mobile,NaN,2026-02-10T01:00:00.000,2026-02-10T03:05:43.000,EXCELSIOR AVE,NaN
1783,101001812451,2025-04-23 15:03:37,2026-02-08T13:02:39.000,Open,open,311 - Supervisor,General Request,municipal_transportation_agency,paint_shop request_for_service,"INTERSECTION MONTEREY BLVD, EL VERANO WAY, SAN...",...,37.7300219512,-122.4617366428,"{'latitude': '37.7300219512', 'longitude': '-1...","{'type': 'Point', 'coordinates': [-122.4617366...",Phone,NaN,2026-02-10T01:00:00.000,2026-02-10T03:05:43.000,MONTEREY BLVD,NaN

In [ ]:
df_history = pd.read_csv('../311_Cases_historic.csv')
df_history['Opened'] = pd.to_datetime(df_history['Opened'])
df_history.sort_values(by='Opened', inplace=True, ascending=False)
df_history.head()

,CaseID,Opened,Closed,Updated,Status,Status Notes,Responsible Agency,Category,Request Type,Request Details,...,Police District,Latitude,Longitude,Point,point_geom,Source,Media URL,BOS_2012,data_as_of,data_loaded_at
0,13437452,02/01/2021 07:48:00 AM,02/02/2021 09:25:00 AM,02/02/2021 09:25:00 AM,Closed,Case Resolved,DPW Ops Queue,Street and Sidewalk Cleaning,General Cleaning,Other Loose Garbage,...,MISSION,37.759908,-122.420728,"(37.75990792, -122.42072815)",POINT (-122.420728148 37.759907915),Mobile/Open311,http://mobile311.sfgov.org/reports/13437452/ph...,9.0,2024/02/20 10:35:55 AM,2024/09/11 05:09:50 PM
1,9657146,10/11/2018 09:51:00 AM,10/11/2018 10:59:00 AM,10/11/2018 10:59:00 AM,Closed,Case Resolved,DPW Ops Queue,Street and Sidewalk Cleaning,Human or Animal Waste,Human or Animal Waste,...,CENTRAL,37.804348,-122.411897,"(37.804348, -122.411897)",POINT (-122.411897 37.804348),Mobile/Open311,NaN,3.0,2024/02/20 10:35:55 AM,2024/09/11 05:09:50 PM
2,13461310,02/06/2021 03:55:00 PM,02/06/2021 07:38:53 PM,02/06/2021 07:38:53 PM,Closed,Case Resolved - Completed,DPW Ops Queue,Street and Sidewalk Cleaning,General Cleaning,Other Loose Garbage,...,RICHMOND,37.776260,-122.487518,"(37.7762595, -122.48751847)",POINT (-122.487518467 37.776259501),Mobile/Open311,http://mobile311.sfgov.org/reports/13461310/ph...,1.0,2024/02/20 10:35:55 AM,2024/09/11 05:09:50 PM
3,13465537,02/08/2021 08:06:00 AM,02/09/2021 10:37:00 AM,02/09/2021 10:37:00 AM,Closed,Case Resolved,DPW Ops Queue,Street and Sidewalk Cleaning,Human or Animal Waste,Human or Animal Waste,...,BAYVIEW,37.727440,-122.384362,"(37.72744017, -122.38436188)",POINT (-122.38436188 37.727440167),Mobile/Open311,http://mobile311.sfgov.org/reports/13465537/ph...,10.0,2024/02/20 10:35:55 AM,2024/09/11 05:09:50 PM
4,13475791,02/10/2021 11:26:00 AM,02/12/2021 09:10:24 AM,02/12/2021 09:10:24 AM,Closed,Case Resolved - WASTE NOT FOUND,Recology_Abandoned,Street and Sidewalk Cleaning,Bulky Items,Boxed or Bagged Items,...,MISSION,37.768272,-122.419983,"(37.7682724, -122.41998291)",POINT (-122.41998291 37.7682724),Phone,NaN,9.0,2024/02/20 10:35:55 AM,2024/09/11 05:09:50 PM

In [127]:
df_history.loc[df_history['Opened'].dt.strftime('%Y-%m-%d') == '2026-02-04']

,CaseID,Opened,Closed,Updated,Status,Status Notes,Responsible Agency,Category,Request Type,Request Details,...,Police District,Latitude,Longitude,Point,point_geom,Source,Media URL,BOS_2012,data_as_of,data_loaded_at
8080613,101003444353,2026-02-04 22:28:21,NaN,02/04/2026 10:28:43 PM,Open,new,Recology - Abandoned,Street and Sidewalk Cleaning,garbage_and_debris,furniture,...,NORTHERN,37.790952,-122.430839,"(37.7909518767999, -122.43083899751026)",POINT (-122.430838998 37.790951877),Mobile,https://spot-sf-res.cloudinary.com/image/uploa...,NaN,2026/02/05 01:00:00 AM,2026/02/05 03:04:48 AM
8081685,101003444348,2026-02-04 22:26:01,NaN,02/04/2026 10:26:16 PM,Open,open,PW - Street Use and Mapping,Sidewalk and Curb,missing_side_sewer_vent_cover,NaN,...,TARAVAL,37.762430,-122.500249,"(37.76243003830206, -122.50024930081453)",POINT (-122.500249301 37.762430038),Mobile,https://spot-sf-res.cloudinary.com/image/uploa...,NaN,2026/02/05 01:00:00 AM,2026/02/05 03:04:48 AM
8079777,101003444347,2026-02-04 22:24:06,NaN,02/04/2026 10:25:29 PM,Open,in progress,PW - Street and Environmental Services,Graffiti Public,not_offensive,city_receptacle,...,TARAVAL,37.753838,-122.495133,"(37.753837604119795, -122.49513253569602)",POINT (-122.495132536 37.753837604),Mobile,https://spot-sf-res.cloudinary.com/image/uploa...,NaN,2026/02/05 01:00:00 AM,2026/02/05 03:04:48 AM
8081915,101003444346,2026-02-04 22:23:40,NaN,02/04/2026 10:25:27 PM,Open,open,PW - Street and Environmental Services,Graffiti Public,not_offensive,transit_shelter_platform,...,TARAVAL,37.753811,-122.495110,"(37.75381083047046, -122.49510973691939)",POINT (-122.495109737 37.75381083),Mobile,https://spot-sf-res.cloudinary.com/image/uploa...,NaN,2026/02/05 01:00:00 AM,2026/02/05 03:04:48 AM
8081132,101003444345,2026-02-04 22:23:24,NaN,02/04/2026 10:29:26 PM,Open,open,PUC - Streetlights,Streetlights,light,light_burnt_out,...,SOUTHERN,37.786149,-122.387898,"(37.786149340097325, -122.38789793257932)",POINT (-122.387897933 37.78614934),Mobile,https://spot-sf-res.cloudinary.com/image/uploa...,NaN,2026/02/05 01:00:00 AM,2026/02/05 03:04:48 AM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8080505,101003437291,2026-02-04 01:01:37,02/04/2026 06:30:42 AM,02/04/2026 06:30:42 AM,Closed,Accepted - Noise informational reports are clo...,Noise Report,Noise,other_excessive_noise,NaN,...,INGLESIDE,37.709822,-122.433515,"(37.709822413005384, -122.4335146876022)",POINT (-122.433514688 37.709822413),Mobile,NaN,NaN,2026/02/05 01:00:00 AM,2026/02/05 03:04:48 AM
8081198,101003437288,2026-02-04 00:52:35,NaN,02/04/2026 01:02:06 AM,Open,in progress,PW - Street and Environmental Services,Street and Sidewalk Cleaning,garbage_and_debris,human_waste_or_urine,...,MISSION,37.762790,-122.419649,"(37.76278997, -122.41964924)",POINT (-122.41964924 37.76278997),Phone,NaN,NaN,2026/02/05 01:00:00 AM,2026/02/05 03:04:48 AM
8080964,101003437283,2026-02-04 00:32:42,02/04/2026 07:32:18 AM,02/04/2026 07:32:30 AM,Closed,Unable to Locate,Recology - Abandoned,Street and Sidewalk Cleaning,garbage_and_debris,furniture,...,NORTHERN,37.774451,-122.432717,"(37.774450821487385, -122.43271737855308)",POINT (-122.432717379 37.774450821),Mobile,https://spot-sf-res.cloudinary.com/image/uploa...,NaN,2026/02/05 01:00:00 AM,2026/02/05 03:04:48 AM
8081643,101003437282,2026-02-04 00:32:25,02/04/2026 06:30:42 AM,02/04/2026 06:30:42 AM,Closed,Accepted - Noise informational reports are clo...,Noise Report,Noise,other_excessive_noise,NaN,...,BAYVIEW,37.727821,-122.370126,"(37.72782119632203, -122.37012637226516)",POINT (-122.370126372 37.727821196),Mobile,https://spot-sf-res.cloudinary.com/image/uploa...,NaN,2026/02/05 01:00:00 AM,2026/02/05 03:04:48 AM
8080943,101003437275,2026-02-04 00:18:31,02/04/2026 11:46:28 AM,02/04/2026 11:46:29 AM,Closed,Not Accepted - Please contact SFPD 415-553-0123,311 - Supervisor,Residential Building,illegal_guest_room_conversions,NaN,...,INGLESIDE,37.742298,-122.417905,"(37.742298, -122.41790455)",POINT (-122.41790455 37.742298),Web,NaN,NaN,2026/02/05 01:00:00 AM,2026/02/05 03:04:48 AM

In [232]:
df_history.loc[df_history['CaseID'] == 101001291088]

,CaseID,Opened,Closed,Updated,Status,Status Notes,Responsible Agency,Category,Request Type,Request Details,...,Police District,Latitude,Longitude,Point,point_geom,Source,Media URL,BOS_2012,data_as_of,data_loaded_at
7585413,101001291088,2025-01-10 10:47:53,NaN,01/10/2025 11:55:04 AM,Open,open,MTA - Paint Shop,General Request,municipal_transportation_agency,paint_shop request_for_service,...,CENTRAL,37.78891,-122.418656,"(37.788909591, -122.4186558658)",POINT (-122.418655866 37.788909591),Phone,NaN,NaN,2025/01/20 06:00:00 AM,2025/01/21 09:01:25 AM

In [234]:
df.loc[df['service_request_id'] == '101001291088']

,service_request_id,requested_datetime,updated_datetime,status_description,status_notes,agency_responsible,service_name,service_subtype,service_details,address,...,lat,long,point,point_geom,source,media_url,data_as_of,data_loaded_at,street,closed_date
1478,101001291088,2025-01-10 10:47:53,2026-02-08T12:17:41.000,Closed,Case is a Duplicate,MTA - Transportation Engineering,General Request,municipal_transportation_agency,paint_shop request_for_service,"INTERSECTION LARKIN ST, BUSH ST, SAN FRANCISCO...",...,37.788909591,-122.4186558658,"{'latitude': '37.788909591', 'longitude': '-12...","{'type': 'Point', 'coordinates': [-122.4186558...",Phone,NaN,2026-02-10T01:00:00.000,2026-02-10T03:05:43.000,LARKIN ST,2026-02-08T12:17:41.000